---
name: Build and Push Ruby on Rails Hello World Image to Google Cloud Platform
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hwrailsapp
      PROJECT_ID: terraform-353823
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build Docker Image
        run: docker build -t hwrailsapp:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.0.1
        run: |-
          docker tag hwrailsapp:latest gcr.io/$PROJECT_ID/hwrailsapp:latest
          docker tag hwrailsapp:latest gcr.io/$PROJECT_ID/hwrailsapp:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/hwrailsapp:latest
          docker push gcr.io/$PROJECT_ID/hwrailsapp:$GIT_TAG

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.0.1
        run: |-
          docker tag hwrailsapp:latest us-east4-docker.pkg.dev/$PROJECT_ID/images/hwrailsapp:latest
          docker tag hwrailsapp:latest us-east4-docker.pkg.dev/$PROJECT_ID/images/hwrailsapp:$GIT_TAG
          docker push us-east4-docker.pkg.dev/$PROJECT_ID/images/hwrailsapp:latest
          docker push us-east4-docker.pkg.dev/$PROJECT_ID/images/hwrailsapp:$GIT_TAG
